export const resList = [
    {
        id: 1,
        name : "Bunny Foods",
        cuisine : "Biryani, South India",
        rating : "4.5",
        deliveryTime : "38 min",
        cost: "250.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs1E7DtscFpZ5Fgz9tyTDHOiZSldAfJZFz2A&s",
    },
    {
        id: 2,
        name : "KFC",
        cuisine : "Chicken, South India",
        rating : "4.6",
        deliveryTime : "25 min",
        cost: "350.00",
        img : "https://b.zmtcdn.com/data/pictures/chains/4/2800014/03930951272152d62dfc165ae8b63d7c.jpg?fit=around|750:500&crop=750:500;*,*",
    },
    {
        id: 3,
        name : "Yummy Tummy",
        cuisine : "Biryani, South India",
        rating : "4.1",
        deliveryTime : "40 min",
        cost: "280.00",
        img : "https://www.licious.in/blog/wp-content/uploads/2023/01/Shutterstock_2047827035.jpg",
    },
    {
        id: 4,
        name : "Red Cherry",
        cuisine : "Pastry and cakes",
        rating : "4.7",
        deliveryTime : "20 min",
        cost: "650.00",
        img : "https://justbakedcake.com/wp-content/uploads/2020/09/Chocochip-pastry.jpg",
    },
    {
        id: 5,
        name : "Master Chef",
        cuisine : "Biryani, South India",
        rating : "4.8",
        deliveryTime : "25 min",
        cost: "200.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvdZv9-9AK9epWA8duL-7yJYrvMJHvveDjQ&s",
    },
    {
        id: 6,
        name : "Bunny Foods",
        cuisine : "Biryani, South India",
        rating : "4.5",
        deliveryTime : "38 min",
        cost: "180.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs1E7DtscFpZ5Fgz9tyTDHOiZSldAfJZFz2A&s",
    },
    {
        id: 7,
        name : "KFC",
        cuisine : "Chicken, South India",
        rating : "4.6",
        deliveryTime : "25 min",
        cost: "450.00",
        img : "https://b.zmtcdn.com/data/pictures/chains/4/2800014/03930951272152d62dfc165ae8b63d7c.jpg?fit=around|750:500&crop=750:500;*,*",
    },
    {
        id: 8,
        name : "Yummy Tummy",
        cuisine : "Biryani, South India",
        rating : "4.1",
        deliveryTime : "40 min",
        cost: "165.00",
        img : "https://www.licious.in/blog/wp-content/uploads/2023/01/Shutterstock_2047827035.jpg",
    },
    {
        id: 9,
        name : "Red Cherry",
        cuisine : "Pastry and cakes",
        rating : "4.7",
        deliveryTime : "20 min",
        cost: "99.00",
        img : "https://justbakedcake.com/wp-content/uploads/2020/09/Chocochip-pastry.jpg",
    },
    {
        id: 10,
        name : "Master Chef",
        cuisine : "Biryani, South India",
        rating : "4.8",
        deliveryTime : "25 min",
        cost: "369.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvdZv9-9AK9epWA8duL-7yJYrvMJHvveDjQ&s",
    },
    {
        id: 11,
        name : "Bunny Foods",
        cuisine : "Biryani, South India",
        rating : "4.5",
        deliveryTime : "38 min",
        cost: "546.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs1E7DtscFpZ5Fgz9tyTDHOiZSldAfJZFz2A&s",
    },
    {
        id: 12,
        name : "KFC",
        cuisine : "Chicken, South India",
        rating : "4.6",
        deliveryTime : "25 min",
        cost: "354.00",
        img : "https://b.zmtcdn.com/data/pictures/chains/4/2800014/03930951272152d62dfc165ae8b63d7c.jpg?fit=around|750:500&crop=750:500;*,*",
    },
    {
        id: 13,
        name : "Yummy Tummy",
        cuisine : "Biryani, South India",
        rating : "4.1",
        deliveryTime : "40 min",
        cost: "212.00",
        img : "https://www.licious.in/blog/wp-content/uploads/2023/01/Shutterstock_2047827035.jpg",
    },
    {
        id: 14,
        name : "Red Cherry",
        cuisine : "Pastry and cakes",
        rating : "4.1",
        deliveryTime : "20 min",
        cost: "123.00",
        img : "https://justbakedcake.com/wp-content/uploads/2020/09/Chocochip-pastry.jpg",
    },
    {
        id: 15,
        name : "Master Chef",
        cuisine : "Biryani, South India",
        rating : "3.9",
        deliveryTime : "25 min",
        cost: "312.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvdZv9-9AK9epWA8duL-7yJYrvMJHvveDjQ&s",
    },
    {
        id: 16,
        name : "Bunny Foods",
        cuisine : "Biryani, South India",
        rating : "3.5",
        deliveryTime : "38 min",
        cost: "453.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs1E7DtscFpZ5Fgz9tyTDHOiZSldAfJZFz2A&s",
    },
    {
        id: 17,
        name : "KFC",
        cuisine : "Chicken, South India",
        rating : "3.6",
        deliveryTime : "25 min",
        cost: "545.00",
        img : "https://b.zmtcdn.com/data/pictures/chains/4/2800014/03930951272152d62dfc165ae8b63d7c.jpg?fit=around|750:500&crop=750:500;*,*",
    },
    {
        id: 18,
        name : "Yummy Tummy",
        cuisine : "Biryani, South India",
        rating : "4.1",
        deliveryTime : "40 min",
        cost: "354.00",
        img : "https://www.licious.in/blog/wp-content/uploads/2023/01/Shutterstock_2047827035.jpg",
    },
    {
        id: 19,
        name : "Red Cherry",
        cuisine : "Pastry and cakes",
        rating : "3.2",
        deliveryTime : "20 min",
        cost: "432.00",
        img : "https://justbakedcake.com/wp-content/uploads/2020/09/Chocochip-pastry.jpg",
    },
    {
        id: 20,
        name : "Master Chef",
        cuisine : "Biryani, South India",
        rating : "3.8",
        deliveryTime : "25 min",
        cost: "129.00",
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvdZv9-9AK9epWA8duL-7yJYrvMJHvveDjQ&s",
    },
]